ALTER TABLE recipes ADD COLUMN meal_type VARCHAR(50);
ALTER TABLE recipes ADD COLUMN dietary_restriction VARCHAR(50);
ALTER TABLE recipes ADD COLUMN country VARCHAR(50);
ALTER TABLE recipes ADD COLUMN cook_time INTEGER;
ALTER TABLE recipes ADD COLUMN servings INTEGER;
ALTER TABLE recipes ADD COLUMN approved BOOLEAN DEFAULT FALSE;